from models.create_location_models.model_location_pg import RackConfig, FloorConfig, KeyLoc

def list_config_wh3() -> list:
	config_wh3 = [
		#KHO 3
		#G1 Racks
		RackConfig(
			name_rack = "G1",
			from_bin = 0,
			to_bin = 31,
			level_config = {"A": 1, "B": 2, "C": 3, "D": 4, "E": 5, "F": 6, "G": 7, "H": 8, "I": 9, "K": 10},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.ST,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.LOW,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Stauts_Location.OK,
			note = None
			),
		#G1 Racks Sheving
		RackConfig(
			name_rack = "G1",
			from_bin = 15,
			to_bin = 31,
			level_config = {"A1": 1, "A2": 1, "A3": 1, "A4": 1, "A5": 1, "A6": 1, "A7": 1, "A8": 1},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.SV,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.LOW,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Stauts_Location.OK,
			note = None
			),
		#G2 Racks
		RackConfig(
			name_rack = "G2",
			from_bin = 0,
			to_bin = 31,
			level_config = {"A": 1, "B": 2, "C": 3, "D": 4, "E": 5, "F": 6, "G": 7, "H": 8},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.ST,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.LOW,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Stauts_Location.OK,
			note = None
			),
		#G3 Racks
		RackConfig(
			name_rack = "G3",
			from_bin = 0,
			to_bin = 34,
			level_config = {"A": 1, "B": 2, "C": 3, "D": 4, "E": 5, "F": 6, "G": 7},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.ST,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Stauts_Location.OK,
			note = None
			),
		#G4 Racks
		RackConfig(
			name_rack = "G4",
			from_bin = 0,
			to_bin = 34,
			level_config = {"A": 1, "B": 2, "C": 3, "D": 4, "E": 5, "F": 6, "G": 7},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Stauts_Location.OK,
			note = None
			),
		#G5 Racks
		RackConfig(
			name_rack = "G5",
			from_bin = 0,
			to_bin = 17,
			level_config = {"A": 1, "B": 2, "C": 3, "D": 4, "E": 5},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Stauts_Location.OK,
			note = None
			),
		RackConfig(
			name_rack = "G5",
			from_bin = 18,
			to_bin = 20,
			level_config = {"C": 3, "D": 4, "E": 5},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Stauts_Location.OK,
			note = KeyLoc.Note.WW_MID_WH
			),
		RackConfig(
			name_rack = "G5",
			from_bin = 21,
			to_bin = 36,
			level_config = {"A": 1, "B": 2, "C": 3, "D": 4, "E": 5},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Stauts_Location.OK,
			note = None
			),
		#G6 Racks
		RackConfig(
			name_rack = "G6",
			from_bin = 0,
			to_bin = 3,
			level_config = {"A": 1, "B": 2, "C": 3, "D": 4, "E": 5},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Stauts_Location.OK,
			note = None
			),
		RackConfig(
			name_rack = "G6",
			from_bin = 4,
			to_bin = 4,
			level_config = {"A": 1, "B": 2, "C": 3, "D": 4, "E": 5},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Stauts_Location.OK,
			note = KeyLoc.Note.VUONG_COT
			),
		RackConfig(
			name_rack = "G6",
			from_bin = 5,
			to_bin = 9,
			level_config = {"A": 1, "B": 2, "C": 3, "D": 4, "E": 5},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Stauts_Location.OK,
			note = None
			),
		RackConfig(
			name_rack = "G6",
			from_bin = 10,
			to_bin = 10,
			level_config = {"A": 1, "B": 2, "C": 3, "D": 4, "E": 5},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Stauts_Location.OK,
			note = KeyLoc.Note.VUONG_COT
			),
		RackConfig(
			name_rack = "G6",
			from_bin = 11,
			to_bin = 15,
			level_config = {"A": 1, "B": 2, "C": 3, "D": 4, "E": 5},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Stauts_Location.OK,
			note = None
			),
		RackConfig(
			name_rack = "G6",
			from_bin = 16,
			to_bin = 16,
			level_config = {"A": 1, "B": 2, "C": 3, "D": 4, "E": 5},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Stauts_Location.OK,
			note = KeyLoc.Note.VUONG_COT
			),
		RackConfig(
			name_rack = "G6",
			from_bin = 17,
			to_bin = 17,
			level_config = {"A": 1, "B": 2, "C": 3, "D": 4, "E": 5},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Stauts_Location.OK,
			note = None
			),
		RackConfig(
			name_rack = "G6",
			from_bin = 18,
			to_bin = 20,
			level_config = {"C": 3, "D": 4, "E": 5},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Stauts_Location.OK,
			note = KeyLoc.Note.WW_MID_WH
			),
		RackConfig(
			name_rack = "G6",
			from_bin = 21,
			to_bin = 21,
			level_config = {"A": 1, "B": 2, "C": 3, "D": 4, "E": 5},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Stauts_Location.OK,
			note = None
			),
		#G7 Racks
		RackConfig(
			name_rack = "G7",
			from_bin = 0,
			to_bin = 17,
			level_config = {"A": 1, "B": 2, "C1": 3, "C2": 3, "D1": 4, "D2": 4, "E1": 5, "E2": 5, "F1": 6, "F2": 6, "G": 7},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Stauts_Location.OK,
			note = None
			),
		RackConfig(
			name_rack = "G7",
			from_bin = 18,
			to_bin = 20,
			level_config = {"D": 4, "E": 5, "F": 6, "G": 7},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Stauts_Location.OK,
			note = KeyLoc.Note.WW_MID_WH
			),
		RackConfig(
			name_rack = "G7",
			from_bin = 21,
			to_bin = 21,
			level_config = {"A": 1, "B": 2, "C": 3, "D": 4, "E": 5, "F": 6, "G": 7},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Stauts_Location.OK,
			note = None
			),
		#G8 Racks
		RackConfig(
			name_rack = "G8",
			from_bin = 0,
			to_bin = 17,
			level_config = {"A": 1, "B": 2, "C": 3, "D": 4, "E": 5, "F": 6, "G": 7},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Stauts_Location.OK,
			note = None
			),
		RackConfig(
			name_rack = "G8",
			from_bin = 18,
			to_bin = 20,
			level_config = {"D": 4, "E": 5, "F": 6, "G": 7},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Stauts_Location.OK,
			note = KeyLoc.Note.WW_MID_WH
			),
		RackConfig(
			name_rack = "G8",
			from_bin = 21,
			to_bin = 21,
			level_config = {"A": 1, "B": 2, "C": 3, "D": 4, "E": 5, "F": 6, "G": 7},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Stauts_Location.OK,
			note = None
			),
		#G9 Racks
		RackConfig(
			name_rack = "G9",
			from_bin = 0,
			to_bin = 12,
			level_config = {"A": 1, "B": 2, "C": 3, "D": 4, "E": 5, "F": 6},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Stauts_Location.OK,
			note = None
			),
		#G10 Racks
		RackConfig(
			name_rack = "G10",
			from_bin = 0,
			to_bin = 9,
			level_config = {"A": 1, "B": 2, "C": 3, "D": 4, "E": 5, "F": 6},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.ST,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Stauts_Location.OK,
			note = None
			),
		RackConfig(
			name_rack = "G10",
			from_bin = 10,
			to_bin = 12,
			level_config = {"A": 1, "B": 2, "C": 3, "D": 4, "E": 5, "F": 6},
			list_bin_ho = [],
			location_usage_type = {10: KeyLoc.LocSystemType.REJECT, 11: KeyLoc.LocSystemType.REJECT, 12: KeyLoc.LocSystemType.REJECT},
			rack_system_type = KeyLoc.RackSystemType.ST,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Stauts_Location.OK,
			note = KeyLoc.Note.BIN_DAMAGE
			),
		RackConfig(
			name_rack = "G10",
			from_bin = 11,
			to_bin = 12,
			level_config = {"A1": 1, "A2": 1, "A3": 1, "A4": 1, "A5": 1, "A6": 1, "A7": 1, "A8": 1},
			list_bin_ho = [],
			location_usage_type = {10: KeyLoc.LocSystemType.REJECT, 11: KeyLoc.LocSystemType.REJECT, 12: KeyLoc.LocSystemType.REJECT},
			rack_system_type = KeyLoc.RackSystemType.SV,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.LOW,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Stauts_Location.OK,
			note = KeyLoc.Note.BIN_DAMAGE
			),
		#ST KHO 3
		#ST ĐƯỜNG LUỒNG KHO 3
		FloorConfig(
			location_name = ['WH3G1', 'WH3G3', 'WH3G5', 'WH3G9', 'WH3G7', 'WH3G1G2', 'WH3G3G4', 'WH3G5G6', 'WH3G7G8', 'WH3ST15',
               'HOG2G3', 'HOG4G5', 'HOG8G9', 'HOG6G7', 'RJG10F'],
			location_system_type = KeyLoc.LocSystemType.WW,
			rack_system_type = KeyLoc.RackSystemType.FL,
			location_storage_type = KeyLoc.LocStorageType.FLOOR,
			zone = KeyLoc.Zone.WH3_WW,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			pallet_capacity = 1,
			stack_limit = 1,
			is_active = [],
			status_location = KeyLoc.Stauts_Location.OK,
			note = None
			),
	]

	return config_wh3