from models.create_location_models.model_location_pg import RackConfig, FloorConfig, KeyLoc

def list_config_wh2() -> list:
	config_wh2 = [
		#KHO 2
		#FA Racks
		RackConfig(
			name_rack = "FA",
			from_bin = 1,
			to_bin = 31,
			level_config = {"A": 1, "B1": 2, "B2": 2, "C1": 3, "C2": 3, "D1": 4, "D2": 4, "E": 5},
			list_bin_ho = [], #[9, 10, 20, 21]
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH2_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			stack_limit = 1,
			is_active = {}, #{9: ['A'], 10: ['A'], 20: ['A'], 21: ['A']}
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		#FB Racks
		RackConfig(
			name_rack = "FB",
			from_bin = 1,
			to_bin = 33,
			level_config = {"A": 1, "B": 2, "C": 3, "D": 4, "E": 5},
			list_bin_ho = [], #[10, 11, 22, 23]
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH2_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			stack_limit = 1,
			is_active = {}, #{10: ['A'], 11: ['A'], 22: ['A'], 23: ['A']}
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		#FC Racks
		RackConfig(
			name_rack = "FC",
			from_bin = 1,
			to_bin = 34,
			level_config = {"A": 1, "B": 2, "C": 3, "D": 4, "E": 5},
			list_bin_ho = [], #[12, 13, 23, 24]
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH2_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			stack_limit = 1,
			is_active = {}, #{12: ['A'], 13: ['A'], 23: ['A'], 24: ['A']},
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		#FD Racks
		RackConfig(
			name_rack = "FD",
			from_bin = 1,
			to_bin = 32,
			level_config = {"A": 1, "B1": 2, "B2": 2, "C": 3, "D": 4, "E": 5},
			list_bin_ho = [], #[13, 14, 25, 26],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH2_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			stack_limit = 1,
			is_active = {}, #{13: ['A'], 14: ['A'], 25: ['A'], 26: ['A']},
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		RackConfig(
			name_rack = "FD",
			from_bin = 33,
			to_bin = 36,
			level_config = {"A": 1, "B": 2, "C": 3, "D": 4, "E": 5},
			list_bin_ho = [], #[13, 14, 25, 26],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH2_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			stack_limit = 1,
			is_active = {}, #{13: ['A'], 14: ['A'], 25: ['A'], 26: ['A']},
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.EO_BIN
			),
		#FE Racks
		RackConfig(
			name_rack = "FE",
			from_bin = 1,
			to_bin = 34,
			level_config = {"A": 1, "B": 2, "C": 3, "D": 4, "E": 5, "F": 6},
			list_bin_ho = [], #[12, 13, 23, 24],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH2_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			stack_limit = 1,
			is_active = {}, #{12: ['A'], 13: ['A'], 23: ['A'], 24: ['A']},
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		#FF Racks
		RackConfig(
			name_rack = "FF",
			from_bin = 1,
			to_bin = 36,
			level_config = {"A": 1, "B": 2, "C": 3, "D": 4, "E": 5, "F": 6},
			list_bin_ho = [], #[13, 14, 25, 26],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH2_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			stack_limit = 1,
			is_active = {}, #{13: ['A'], 14: ['A'], 25: ['A'], 26: ['A']},
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		#FG Racks
		RackConfig(
			name_rack = "FG",
			from_bin = 1,
			to_bin = 34,
			level_config = {"A": 1, "B": 2, "C": 3, "D": 4, "E": 5, "F": 6},
			list_bin_ho = [], #[12, 13, 23, 24],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH2_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			stack_limit = 1,
			is_active = {}, #{12: ['A'], 13: ['A'], 23: ['A'], 24: ['A']},
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		#FH Racks
		RackConfig(
			name_rack = "FH",
			from_bin = 1,
			to_bin = 36,
			level_config = {"A": 1, "B": 2, "C": 3, "D": 4, "E": 5, "F": 6},
			list_bin_ho = [], #[13, 14, 25, 26],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH2_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			stack_limit = 1,
			is_active = {}, #{13: ['A'], 14: ['A'], 25: ['A'], 26: ['A']},
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		#FI Racks
		RackConfig(
			name_rack = "FI",
			from_bin = 1,
			to_bin = 34,
			level_config = {"A": 1, "B": 2, "C": 3, "D": 4, "E": 5, "F": 6},
			list_bin_ho = [], #[12, 13, 23, 24],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH2_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			stack_limit = 1,
			is_active = {}, #{12: ['A'], 13: ['A'], 23: ['A'], 24: ['A']},
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		#FK Racks
		RackConfig(
			name_rack = "FK",
			from_bin = 1,
			to_bin = 36,
			level_config = {"A": 1, "B": 2, "C": 3, "D": 4, "E": 5, "F": 6},
			list_bin_ho = [], #[13, 14, 25, 26],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH2_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			stack_limit = 1,
			is_active = {}, #{13: ['A'], 14: ['A'], 25: ['A'], 26: ['A']},
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		#FL Racks
		RackConfig(
			name_rack = "FL",
			from_bin = 1,
			to_bin = 34,
			level_config = {"A": 1, "B": 2, "C": 3, "D": 4, "E": 5},
			list_bin_ho = [], #[12, 13, 23, 24],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH2_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			stack_limit = 1,
			is_active = {}, #{12: ['A'], 13: ['A'], 23: ['A'], 24: ['A']},
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		#FM Racks
		RackConfig(
			name_rack = "FM",
			from_bin = 1,
			to_bin = 36,
			level_config = {"A": 1, "B": 2, "C1": 3, "C2": 3, "D1": 4, "D2": 4, "E": 5},
			list_bin_ho = [], #[13, 14, 25, 26],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH2_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			stack_limit = 1,
			is_active = {}, #{13: ['A'], 14: ['A'], 25: ['A'], 26: ['A']},
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		#DA Obiter Current
		RackConfig(
			name_rack = "DA",
			from_bin = 1,
			to_bin = 30,
			level_config = {"AT": 1, "AN": 1, "BT": 2, "BN": 2, "CT": 3, "CN": 3, "DT": 4, "DN": 4},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.OB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH2_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		#Rack FBC chứa hàng tập kết để 901 cấp lên xưởng
		RackConfig(
			name_rack = "FBC",
			from_bin = 1,
			to_bin = 16,
			level_config = {"AT": 1, "AN": 1},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH2_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			stack_limit = 1,
			is_active = {},
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		#=======================================================================================================================
		#DA Obiter Old. is_active sẽ có giá trị = 0. Đưa vào để chạy tồn kho cũ
		#khi chưa có location mới
		RackConfig(
			name_rack = "DA",
			from_bin = 1,
			to_bin = 30,
			level_config = {key: ord(key[0])-64 for key in ['A', 'B1', "B2", 'C1', 'C2', 'D1', 'D2']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.OB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH2_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			stack_limit = 1,
			is_active = 0,
			status_location = KeyLoc.Status_Location.LOCK,
			note = None
			),
		#Rack HO Old. is_active sẽ có giá trị = 0. Đưa vào để chạy tồn kho cũ
		#Rack HO này đã bỏ không sử dụng nữa
		RackConfig(
			name_rack = ['FA'],
			from_bin = [9, 10, 20, 21],
			to_bin = 0,
			level_config = {key: ord(key[0])-64 for key in ['A']},
			list_bin_ho = [9, 10, 20, 21],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH2_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			stack_limit = 1,
			is_active = 0,
			status_location = KeyLoc.Status_Location.LOCK,
			note = None
			),
		RackConfig(
			name_rack = ['FB'],
			from_bin = [10, 11, 22, 23],
			to_bin = 0,
			level_config = {key: ord(key[0])-64 for key in ['A']},
			list_bin_ho = [10, 11, 22, 23],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH2_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			stack_limit = 1,
			is_active = 0,
			status_location = KeyLoc.Status_Location.LOCK,
			note = None
			),
		RackConfig(
			name_rack = ['FC'],
			from_bin = [12, 13, 23, 24],
			to_bin = 0,
			level_config = {key: ord(key[0])-64 for key in ['A']},
			list_bin_ho = [12, 13, 23, 24],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH2_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			stack_limit = 1,
			is_active = 0,
			status_location = KeyLoc.Status_Location.LOCK,
			note = None
			),
		RackConfig(
			name_rack = ['FD'],
			from_bin = [13, 14, 25, 26],
			to_bin = 0,
			level_config = {key: ord(key[0])-64 for key in ['A']},
			list_bin_ho = [13, 14, 25, 26],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH2_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			stack_limit = 1,
			is_active = 0,
			status_location = KeyLoc.Status_Location.LOCK,
			note = None
			),
		#Tách riêng FC ra vì FC là rack cao
		RackConfig(
			name_rack = ['FE', 'FG', 'FI', 'FL'],
			from_bin = [12, 13, 23, 24],
			to_bin = 0,
			level_config = {key: ord(key[0])-64 for key in ['A']},
			list_bin_ho = [12, 13, 23, 24],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH2_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			stack_limit = 1,
			is_active = 0,
			status_location = KeyLoc.Status_Location.LOCK,
			note = None
			),
		#Tách riêng FD ra vì FD là rack cao
		RackConfig(
			name_rack = ['FF', 'FH', 'FK', 'FM'],
			from_bin = [13, 14, 25, 26],
			to_bin = 0,
			level_config = {key: ord(key[0])-64 for key in ['A']},
			list_bin_ho = [13, 14, 25, 26],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH2_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			stack_limit = 1,
			is_active = 0,
			status_location = KeyLoc.Status_Location.LOCK,
			note = None
			),
		#=======================================================================================================================
		#ST KHO 2
		#ST234
		FloorConfig(
			location_name = ['ST01', 'ST02', 'ST03', 'ST04'],
			location_system_type = KeyLoc.LocSystemType.IN,
			rack_system_type = KeyLoc.RackSystemType.FL,
			location_storage_type = KeyLoc.LocStorageType.FLOOR,
			zone = KeyLoc.Zone.WH2_IN,
			location_category = KeyLoc.LocCategory.RECEIVING,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			pallet_capacity = 1,
			stack_limit = 1,
			is_active = [],
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		#ST ĐƯỜNG LUỒNG KHO 2
		FloorConfig(
			location_name = ['WH2FA', 'WH2FB', 'WH2FC', 'WH2FD', 'WH2FF', 'WH2FH', 'WH2FK', 'WH2FM', 'HOFA', 'HOFBFC', 'HOFDFF', 'HOFFFG', 'HOFHFI', 'HOFKFL', 'HOFMF9'],
			location_system_type = KeyLoc.LocSystemType.WW,
			rack_system_type = KeyLoc.RackSystemType.FL,
			location_storage_type = KeyLoc.LocStorageType.FLOOR,
			zone = KeyLoc.Zone.WH2_WW,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			pallet_capacity = 1,
			stack_limit = 1,
			is_active = [],
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		#ST OUT
		FloorConfig(
			location_name = ['ST' + str(i).zfill(2) for i in range(5, 17)],
			location_system_type = KeyLoc.LocSystemType.PICK,
			rack_system_type = KeyLoc.RackSystemType.FL,
			location_storage_type = KeyLoc.LocStorageType.FLOOR,
			zone = KeyLoc.Zone.WH2_FLOOR,
			location_category = KeyLoc.LocCategory.PICKING,
			location_product_category = KeyLoc.LocProducCategory.OTHER,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			pallet_capacity = 1,
			stack_limit = 1,
			is_active = [],
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		#LOCATION REWORK
		FloorConfig(
			location_name = ['FGLS', 'FGDM', 'DMGE', 'MATDM', 'LOST'],
			location_system_type = KeyLoc.LocSystemType.REWORK,
			rack_system_type = KeyLoc.RackSystemType.FL,
			location_storage_type = KeyLoc.LocStorageType.FLOOR,
			zone = KeyLoc.Zone.WH2_REWORK,
			location_category = KeyLoc.LocCategory.REWORK,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			pallet_capacity = 1,
			stack_limit = 1,
			is_active = [],
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		#LOCATION TRẢ HÀNG LẺ KHI XUẤT HÀNG
		FloorConfig(
			location_name = ['STJP'],
			location_system_type = KeyLoc.LocSystemType.RETURN,
			rack_system_type = KeyLoc.RackSystemType.FL,
			location_storage_type = KeyLoc.LocStorageType.FLOOR,
			zone = KeyLoc.Zone.WH2_RETURN,
			location_category = KeyLoc.LocCategory.RETURN,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			pallet_capacity = 1,
			stack_limit = 1,
			is_active = [],
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		#ST SHIPOUT
		FloorConfig(
			location_name = ['EXW' + str(i) for i in range(1, 11)] + ['C' + str(i).zfill(3) for i in range(1, 201)],
			location_system_type = KeyLoc.LocSystemType.SHIPOUT,
			rack_system_type = KeyLoc.RackSystemType.OTHER,
			location_storage_type = KeyLoc.LocStorageType.OTHER,
			zone = KeyLoc.Zone.WH2_SHIPOUT,
			location_category = KeyLoc.LocCategory.SHIPPING,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			pallet_capacity = 1,
			stack_limit = 1,
			is_active = [],
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		#ST SCANOUT
		FloorConfig(
			location_name = ['DOOR' + str(i).zfill(2) for i in range(1, 101)] + ['CONT' + str(i).zfill(3) for i in range(1, 101)],
			location_system_type = KeyLoc.LocSystemType.SCANOUT,
			rack_system_type = KeyLoc.RackSystemType.OTHER,
			location_storage_type = KeyLoc.LocStorageType.OTHER,
			zone = KeyLoc.Zone.WH2_SCANOUT,
			location_category = KeyLoc.LocCategory.SCANOUT,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			pallet_capacity = 1,
			stack_limit = 1,
			is_active = [],
			status_location = KeyLoc.Status_Location.OK,
			note = None
			)

	]

	return config_wh2