from models.create_location_models.model_location_pg import RackConfig, FloorConfig, KeyLoc

def list_config_wh1_new() -> list:
	'''	Location hệ thống mới chỉ thay đổi location rack
		Location ST, Floor vẫn chạy bên location cũ
	'''
	config_wh1 = [
		#B1 Racks
		RackConfig(
			name_rack = "B01",
			from_bin = 1,
			to_bin = 5,
			level_config = {i:ord(i)-64 for i in ['B', 'C', 'D']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.TANG_A_LSL_LRT_DNDC
			),
		RackConfig(
			name_rack = "B01",
			from_bin = 6,
			to_bin = 8,
			level_config = {i:ord(i)-64 for i in ['C', 'D']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.WW_MID_WH
			),
		RackConfig(
			name_rack = "B01",
			from_bin = 9,
			to_bin = 14,
			level_config = {i:ord(i)-64  for i in ['B', 'C', 'D']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.TANG_A_LSL_LRT_DNDC
			),
		#B2 Racks
		RackConfig(
			name_rack = "B02",
			from_bin = 1,
			to_bin = 5,
			level_config = {i:ord(i)-64  for i in ['B', 'C', 'D']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.TANG_A_LSL_CA
			),
		RackConfig(
			name_rack = "B02",
			from_bin = 6,
			to_bin = 8,
			level_config = {i:ord(i)-64 for i in ['C', 'D']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.WW_MID_WH
			),
		RackConfig(
			name_rack = "B02",
			from_bin = 9,
			to_bin = 14,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		RackConfig(
			name_rack = "B02",
			from_bin = 15,
			to_bin = 16,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.BO_TANG_E_PCCC
			),
		RackConfig(
			name_rack = "B02",
			from_bin = 17,
			to_bin = 20,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		RackConfig(
			name_rack = "B02",
			from_bin = 21,
			to_bin = 23,
			level_config = {i:ord(i)-64 for i in ['C', 'D']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.WW_MID_WH
			),
		RackConfig(
			name_rack = "B02",
			from_bin = 24,
			to_bin = 25,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		#B3 Racks
		RackConfig(
			name_rack = "B03",
			from_bin = 1,
			to_bin = 2,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.BO_TANG_E_PCCC
			),
		RackConfig(
			name_rack = "B03",
			from_bin = 3,
			to_bin = 5,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		RackConfig(
			name_rack = "B03",
			from_bin = 6,
			to_bin = 8,
			level_config = {i:ord(i)-64 for i in ['C', 'D']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.WW_MID_WH
			),
		RackConfig(
			name_rack = "B03",
			from_bin = 9,
			to_bin = 12,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		RackConfig(
			name_rack = "B03",
			from_bin = 13,
			to_bin = 16,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.BO_TANG_E_PCCC
			),
		RackConfig(
			name_rack = "B03",
			from_bin = 17,
			to_bin = 20,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		RackConfig(
			name_rack = "B03",
			from_bin = 21,
			to_bin = 23,
			level_config = {i:ord(i)-64 for i in ['C', 'D']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.WW_MID_WH
			),
		RackConfig(
			name_rack = "B03",
			from_bin = 24,
			to_bin = 26,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		RackConfig(
			name_rack = "B03",
			from_bin = 27,
			to_bin = 28,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.BO_TANG_E_PCCC
			),
		#B4 Racks
		RackConfig(
			name_rack = "B04",
			from_bin = 1,
			to_bin = 2,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.BO_TANG_E_PCCC
			),
		RackConfig(
			name_rack = "B04",
			from_bin = 3,
			to_bin = 5,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.BO_TANG_E_PCCC
			),
		RackConfig(
			name_rack = "B04",
			from_bin = 6,
			to_bin = 8,
			level_config = {i:ord(i)-64 for i in ['C', 'D']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.WW_MID_WH
			),
		RackConfig(
			name_rack = "B04",
			from_bin = 9,
			to_bin = 12,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		RackConfig(
			name_rack = "B04",
			from_bin = 13,
			to_bin = 16,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.BO_TANG_E_PCCC
			),
		RackConfig(
			name_rack = "B04",
			from_bin = 17,
			to_bin = 20,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		RackConfig(
			name_rack = "B04",
			from_bin = 21,
			to_bin = 23,
			level_config = {i:ord(i)-64 for i in ['C', 'D']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.WW_MID_WH
			),
		RackConfig(
			name_rack = "B04",
			from_bin = 24,
			to_bin = 26,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		RackConfig(
			name_rack = "B04",
			from_bin = 27,
			to_bin = 28,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.BO_TANG_E_PCCC
			),
		#B5 Racks
		RackConfig(
			name_rack = "B05",
			from_bin = 1,
			to_bin = 1,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		RackConfig(
			name_rack = "B05",
			from_bin = 2,
			to_bin = 4,
			level_config = {i:ord(i)-64 for i in ['C', 'D']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.BO_TANG_E_PCCC
			),
		RackConfig(
			name_rack = "B05",
			from_bin = 5,
			to_bin = 8,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		RackConfig(
			name_rack = "B05",
			from_bin = 9,
			to_bin = 12,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.BO_TANG_E_PCCC
			),
		RackConfig(
			name_rack = "B05",
			from_bin = 13,
			to_bin = 16,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		#B6 Racks
		RackConfig(
			name_rack = "B06",
			from_bin = 1,
			to_bin = 4,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		RackConfig(
			name_rack = "B06",
			from_bin = 5,
			to_bin = 8,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.BO_TANG_E_PCCC
			),
		RackConfig(
			name_rack = "B06",
			from_bin = 9,
			to_bin = 12,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		#B7 Racks
		# RackConfig(
		# 	name_rack = "B7",
		# 	from_bin = 5,
		# 	to_bin = 8,
		# 	level_config = {"A": 1, "B": 2, "C": 3, "D": 4, "E": 5},
		# 	list_bin_ho = [],
		# 	location_usage_type = {},
		# 	rack_system_type = KeyLoc.RackSystemType.ST,
		# 	location_storage_type = KeyLoc.LocStorageType.RACK,
		# 	zone = KeyLoc.Zone.WH1_RACK,
		# 	location_category = KeyLoc.LocCategory.STORARE,
		# 	location_product_category = KeyLoc.LocProducCategory.FG_RPM,
		# 	location_hight = KeyLoc.LocHight.HIGHT,
		# 	name_warehouse = KeyLoc.NameWarehouse.WH1,
		# 	stack_limit = 1,
		# 	is_active = 1,
		# 	status_location = KeyLoc.Status_Location.OK,
		# 	note = None
		# 	),
		# RackConfig(
		# 	name_rack = "B7",
		# 	from_bin = 9,
		# 	to_bin = 10,
		# 	level_config = {"A": 1, "B": 2, "C": 3, "D": 4},
		# 	list_bin_ho = [],
		# 	location_usage_type = {},
		# 	rack_system_type = KeyLoc.RackSystemType.ST,
		# 	location_storage_type = KeyLoc.LocStorageType.RACK,
		# 	zone = KeyLoc.Zone.WH1_RACK,
		# 	location_category = KeyLoc.LocCategory.STORARE,
		# 	location_product_category = KeyLoc.LocProducCategory.FG_RPM,
		# 	location_hight = KeyLoc.LocHight.HIGHT,
		# 	name_warehouse = KeyLoc.NameWarehouse.WH1,
		# 	stack_limit = 1,
		# 	is_active = 1,
		# 	status_location = KeyLoc.Status_Location.OK,
		# 	note = KeyLoc.Note.BO_TANG_E_PCCC
		# 	),
		# RackConfig(
		# 	name_rack = "B7",
		# 	from_bin = 15,
		# 	to_bin = 18,
		# 	level_config = {"A": 1, "B": 2, "C": 3, "D": 4, "E": 5},
		# 	list_bin_ho = [],
		# 	location_usage_type = {},
		# 	rack_system_type = KeyLoc.RackSystemType.ST,
		# 	location_storage_type = KeyLoc.LocStorageType.RACK,
		# 	zone = KeyLoc.Zone.WH1_RACK,
		# 	location_category = KeyLoc.LocCategory.STORARE,
		# 	location_product_category = KeyLoc.LocProducCategory.FG_RPM,
		# 	location_hight = KeyLoc.LocHight.HIGHT,
		# 	name_warehouse = KeyLoc.NameWarehouse.WH1,
		# 	stack_limit = 1,
		# 	is_active = 1,
		# 	status_location = KeyLoc.Status_Location.OK,
		# 	note = None
		# 	),
		# RackConfig(
		# 	name_rack = "B7",
		# 	from_bin = 19,
		# 	to_bin = 20,
		# 	level_config = {"A": 1, "B": 2, "C": 3, "D": 4},
		# 	list_bin_ho = [],
		# 	location_usage_type = {},
		# 	rack_system_type = KeyLoc.RackSystemType.ST,
		# 	location_storage_type = KeyLoc.LocStorageType.RACK,
		# 	zone = KeyLoc.Zone.WH1_RACK,
		# 	location_category = KeyLoc.LocCategory.STORARE,
		# 	location_product_category = KeyLoc.LocProducCategory.FG_RPM,
		# 	location_hight = KeyLoc.LocHight.HIGHT,
		# 	name_warehouse = KeyLoc.NameWarehouse.WH1,
		# 	stack_limit = 1,
		# 	is_active = 1,
		# 	status_location = KeyLoc.Status_Location.OK,
		# 	note = KeyLoc.Note.BO_TANG_E_PCCC
		# 	),
		#B8 Racks
		RackConfig(
			name_rack = "B08",
			from_bin = 1,
			to_bin = 4,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E', 'F']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		RackConfig(
			name_rack = "B08",
			from_bin = 5,
			to_bin = 6,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.BO_TANG_E_PCCC
			),
		RackConfig(
			name_rack = "B08",
			from_bin = 7,
			to_bin = 8,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.BO_TANG_E_PCCC
			),
		RackConfig(
			name_rack = "BT8",
			from_bin = 7,
			to_bin = 8,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.BO_TANG_E_PCCC
			),
		RackConfig(
			name_rack = "B08",
			from_bin = 9,
			to_bin = 15,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		RackConfig(
			name_rack = "BT8",
			from_bin = 9,
			to_bin = 15,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
	]

	return config_wh1