from models.create_location_models.model_location_pg import RackConfig, FloorConfig, KeyLoc

def list_config_label() -> list:
	config_label = [
		#Kho label
		#LB3
		RackConfig(
			name_rack = "LB3",
			from_bin = 1,
			to_bin = 12,
			level_config = {key: ord(key[0]) - 64 for key in ['A1', 'A2', 'B1', 'B2', 'C1', 'C2', 'D1', 'D2']},
			list_bin_ho= [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.SV,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.LB_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.LOW,
			name_warehouse = KeyLoc.NameWarehouse.LB,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Stauts_Location.OK,
			note = None
			),
		RackConfig(
			name_rack = "LB3",
			from_bin = 18,
			to_bin = 23,
			level_config = {key: ord(key[0]) - 64 for key in ['A1', 'A2', 'A3', 'B1', 'B2', 'B3', 'C1', 'C2', 'C3']},
			list_bin_ho= [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.SV,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.LB_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.LOW,
			name_warehouse = KeyLoc.NameWarehouse.LB,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Stauts_Location.OK,
			note = None
			),
		#LB4
		RackConfig(
			name_rack = "LB4",
			from_bin = 1,
			to_bin = 20,
			level_config = {key: ord(key[0]) - 64 for key in ['A1', 'A2', 'B1', 'B2', 'C1', 'C2', 'D1', 'D2']},
			list_bin_ho= [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.SV,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.LB_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.LOW,
			name_warehouse = KeyLoc.NameWarehouse.LB,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Stauts_Location.OK,
			note = None
			),
		RackConfig(
			name_rack = "LB4",
			from_bin = 21,
			to_bin = 28,
			level_config = {key: ord(key[0]) - 64 for key in ['A1', 'A2', 'A3', 'B1', 'B2', 'B3', 'C1', 'C2', 'C3']},
			list_bin_ho= [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.SV,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.LB_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.LOW,
			name_warehouse = KeyLoc.NameWarehouse.LB,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Stauts_Location.OK,
			note = None
			),
		#LB5
		RackConfig(
			name_rack = "LB5",
			from_bin = 1,
			to_bin = 16,
			level_config = {key: ord(key[0]) - 64 for key in ['A1', 'A2', 'B1', 'B2', 'C1', 'C2', 'D1', 'D2']},
			list_bin_ho= [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.SV,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.LB_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.LOW,
			name_warehouse = KeyLoc.NameWarehouse.LB,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Stauts_Location.OK,
			note = None
			),
		RackConfig(
			name_rack = "LB5",
			from_bin = 21,
			to_bin = 27,
			level_config = {key: ord(key[0]) - 64 for key in ['A1', 'A2', 'B1', 'B2', 'C1', 'C2', 'D1', 'D2']},
			list_bin_ho= [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.SV,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.LB_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.LOW,
			name_warehouse = KeyLoc.NameWarehouse.LB,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Stauts_Location.OK,
			note = None
			),
		#LB6
		RackConfig(
			name_rack = "LB6",
			from_bin = 1,
			to_bin = 16,
			level_config = {key: ord(key[0]) - 64 for key in ['A1', 'A2', 'B1', 'B2', 'C1', 'C2', 'D1', 'D2']},
			list_bin_ho= [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.SV,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.LB_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.LOW,
			name_warehouse = KeyLoc.NameWarehouse.LB,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Stauts_Location.OK,
			note = None
			),
		RackConfig(
			name_rack = "LB6",
			from_bin = 21,
			to_bin = 27,
			level_config = {key: ord(key[0]) - 64 for key in ['A1', 'A2', 'B1', 'B2', 'C1', 'C2', 'D1', 'D2']},
			list_bin_ho= [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.SV,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.LB_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.LOW,
			name_warehouse = KeyLoc.NameWarehouse.LB,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Stauts_Location.OK,
			note = None
			),
		#LB7
		RackConfig(
			name_rack = "LB7",
			from_bin = 18,
			to_bin = 23,
			level_config = {key: ord(key[0]) - 64 for key in ['A1', 'A2', 'B1', 'B2', 'C1', 'C2', 'D1', 'D2']},
			list_bin_ho= [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.SV,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.LB_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.LOW,
			name_warehouse = KeyLoc.NameWarehouse.LB,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Stauts_Location.OK,
			note = None
			),
		#LB7 EO
		RackConfig(
			name_rack = "LB7",
			from_bin = 17,
			to_bin = 17,
			level_config = {key: ord(key[0]) - 64 for key in ['A1', 'A2', 'A3', 'B1', 'B2', 'B3', 'C1', 'C2', 'C3', 'D1', 'D2', 'D3']},
			list_bin_ho= [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.SV,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.LB_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.LOW,
			name_warehouse = KeyLoc.NameWarehouse.LB,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Stauts_Location.OK,
			note = KeyLoc.Note.LB_EO
			),
		#ST KHO LABEL
		FloorConfig(
			location_name = ['LABEL1', 'LABEL2', 'LABEL3', 'LABEL4', 'LABEL5', 'LABEL6', 'LABEL7', 'STLB', 'LBSTEAM'],
			location_system_type = KeyLoc.LocSystemType.WW,
			rack_system_type = KeyLoc.RackSystemType.FL,
			location_storage_type = KeyLoc.LocStorageType.FLOOR,
			zone = KeyLoc.Zone.LB_FLOOR,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			name_warehouse = KeyLoc.NameWarehouse.LB,
			pallet_capacity = 1,
			stack_limit = 1,
			is_active = [],
			status_location = KeyLoc.Stauts_Location.OK,
			note = None
			),
	]

	return config_label