[theme]
# Primary accent for interactive elements
primaryColor = '#7792E3'

# Background color for the main content area
backgroundColor = '#273346'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#B9F1C0'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"

#======ngrok===========
[server]
port = 8080
# Bắt buộc Streamlit sử dụng cùng một host cho kết nối websocket
# Tuy nhiên, trong tunnel, điều này có thể bị bỏ qua để giải quyết lỗi
# Nhưng nếu bạn có firewall, hãy đảm bảo cổng này được mở.
headless = true
enableCORS = true
enableXsrfProtection = true