# import sys
# import os

# # Lấy đường dẫn tuyệt đối của thư mục chứa file main.py
# current_dir = os.path.dirname(os.path.abspath(__file__))
# # Lấy đường dẫn của thư mục cha (nơi chứa thư mục models)
# parent_dir = os.path.dirname(current_dir)

# # Thêm thư mục cha vào sys.path
# sys.path.append(parent_dir)

from models.create_location_models.model_location_pg import KeyLoc
from models.create_location_models.location_pg_new.model_location_pg_new import RackConfig_New

#python -m models.create_location_models.location_pg_new.location_wh1_new
def list_config_wh1_new() -> list:
	'''	Location hệ thống mới chỉ thay đổi location rack
		Location ST, Floor vẫn chạy bên location cũ
	'''
	config_wh1_new = [
		#B1 Racks
		RackConfig_New(
			name_rack = ['B01'],
			from_bin = 1,
			to_bin = 5,
			level_config = {i:ord(i)-64 for i in ['B', 'C', 'D']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.TANG_A_LSL_LRT_DNDC
			),
		RackConfig_New(
			name_rack = ['B01'],
			from_bin = 6,
			to_bin = 8,
			level_config = {i:ord(i)-64 for i in ['C', 'D']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.WW_MID_WH
			),
		RackConfig_New(
			name_rack = ['B01'],
			from_bin = 9,
			to_bin = 14,
			level_config = {i:ord(i)-64  for i in ['B', 'C', 'D']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.TANG_A_LSL_LRT_DNDC
			),
		#B2 Racks
		RackConfig_New(
			name_rack = ['B02'],
			from_bin = 1,
			to_bin = 5,
			level_config = {i:ord(i)-64  for i in ['B', 'C', 'D']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.TANG_A_LSL_CA
			),
		RackConfig_New(
			name_rack = ['B02'],
			from_bin = 6,
			to_bin = 8,
			level_config = {i:ord(i)-64 for i in ['C', 'D']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.WW_MID_WH
			),
		RackConfig_New(
			name_rack = ['B02'],
			from_bin = 9,
			to_bin = 14,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		RackConfig_New(
			name_rack = ['B02'],
			from_bin = 15,
			to_bin = 16,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.BO_TANG_E_PCCC
			),
		RackConfig_New(
			name_rack = ['B02'],
			from_bin = 17,
			to_bin = 20,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		RackConfig_New(
			name_rack = ['B02'],
			from_bin = 21,
			to_bin = 23,
			level_config = {i:ord(i)-64 for i in ['C', 'D']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.WW_MID_WH
			),
		RackConfig_New(
			name_rack = ['B02'],
			from_bin = 24,
			to_bin = 25,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		#B3 Racks
		RackConfig_New(
			name_rack = ['B03'],
			from_bin = 1,
			to_bin = 2,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.BO_TANG_E_PCCC
			),
		RackConfig_New(
			name_rack = ['B03'],
			from_bin = 3,
			to_bin = 5,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		RackConfig_New(
			name_rack = ['B03'],
			from_bin = 6,
			to_bin = 8,
			level_config = {i:ord(i)-64 for i in ['C', 'D']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.WW_MID_WH
			),
		RackConfig_New(
			name_rack = ['B03'],
			from_bin = 9,
			to_bin = 12,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		RackConfig_New(
			name_rack = ['B03'],
			from_bin = 13,
			to_bin = 16,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.BO_TANG_E_PCCC
			),
		RackConfig_New(
			name_rack = ['B03'],
			from_bin = 17,
			to_bin = 20,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		RackConfig_New(
			name_rack = ['B03'],
			from_bin = 21,
			to_bin = 23,
			level_config = {i:ord(i)-64 for i in ['C', 'D']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.WW_MID_WH
			),
		RackConfig_New(
			name_rack = ['B03'],
			from_bin = 24,
			to_bin = 26,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		RackConfig_New(
			name_rack = ['B03'],
			from_bin = 27,
			to_bin = 28,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.BO_TANG_E_PCCC
			),
		#B4 Racks
		RackConfig_New(
			name_rack = ['B04'],
			from_bin = 1,
			to_bin = 2,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.BO_TANG_E_PCCC
			),
		RackConfig_New(
			name_rack = ['B04'],
			from_bin = 3,
			to_bin = 5,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.BO_TANG_E_PCCC
			),
		RackConfig_New(
			name_rack = ['B04'],
			from_bin = 6,
			to_bin = 8,
			level_config = {i:ord(i)-64 for i in ['C', 'D']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.WW_MID_WH
			),
		RackConfig_New(
			name_rack = ['B04'],
			from_bin = 9,
			to_bin = 12,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		RackConfig_New(
			name_rack = ['B04'],
			from_bin = 13,
			to_bin = 16,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.BO_TANG_E_PCCC
			),
		RackConfig_New(
			name_rack = ['B04'],
			from_bin = 17,
			to_bin = 20,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		RackConfig_New(
			name_rack = ['B04'],
			from_bin = 21,
			to_bin = 23,
			level_config = {i:ord(i)-64 for i in ['C', 'D']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.WW_MID_WH
			),
		RackConfig_New(
			name_rack = ['B04'],
			from_bin = 24,
			to_bin = 26,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		RackConfig_New(
			name_rack = ['B04'],
			from_bin = 27,
			to_bin = 28,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.BO_TANG_E_PCCC
			),
		#B5 Racks
		RackConfig_New(
			name_rack = ['B05'],
			from_bin = 1,
			to_bin = 1,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		RackConfig_New(
			name_rack = ['B05'],
			from_bin = 2,
			to_bin = 4,
			level_config = {i:ord(i)-64 for i in ['C', 'D']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.BO_TANG_E_PCCC
			),
		RackConfig_New(
			name_rack = ['B05'],
			from_bin = 5,
			to_bin = 8,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		RackConfig_New(
			name_rack = ['B05'],
			from_bin = 9,
			to_bin = 12,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.BO_TANG_E_PCCC
			),
		RackConfig_New(
			name_rack = ['B05'],
			from_bin = 13,
			to_bin = 16,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		#B6 Racks
		RackConfig_New(
			name_rack = ['B06'],
			from_bin = 1,
			to_bin = 4,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		RackConfig_New(
			name_rack = ['B06'],
			from_bin = 5,
			to_bin = 8,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.BO_TANG_E_PCCC
			),
		RackConfig_New(
			name_rack = ['B06'],
			from_bin = 9,
			to_bin = 12,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		#B7 Racks
		RackConfig_New(
			name_rack = ['B07'],
			from_bin = 1,
			to_bin = 4,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			ft_prefix_chars = {'B07': 'BT7'},
			ft_prefix_at_level = {'B07': ['A', 'B', 'C', 'D', 'E']},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
        RackConfig_New(
			name_rack = ['B07'],
			from_bin = 5,
			to_bin = 6,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D']},
			ft_prefix_chars = {'B07': 'BT7'},
			ft_prefix_at_level = {'B07': ['A', 'B', 'C', 'D']},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.BO_TANG_E_PCCC
			),
        RackConfig_New(
			name_rack = ['B07'],
			from_bin = 7,
			to_bin = 8,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.BO_TANG_E_PCCC
			),
        RackConfig_New(
			name_rack = ['B07'],
			from_bin = 9,
			to_bin = 12,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		
		#B8 Racks
		RackConfig_New(
			name_rack = ['B08'],
			from_bin = 1,
			to_bin = 4,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E', 'F']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
		RackConfig_New(
			name_rack = ['B08'],
			from_bin = 5,
			to_bin = 6,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.BO_TANG_E_PCCC
			),
		RackConfig_New(
			name_rack = ['B08'],
			from_bin = 7,
			to_bin = 8,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			ft_prefix_chars = {'B08': 'BT8'},
			ft_prefix_at_level = {'B08': ['A', 'B', 'C', 'D', 'E']},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.BO_TANG_E_PCCC
			),
		RackConfig_New(
			name_rack = ['B08'],
			from_bin = 9,
			to_bin = 15,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E', 'F']},
			ft_prefix_chars = {'B08': 'BT8'},
			ft_prefix_at_level = {'B08': ['A', 'B', 'C', 'D', 'E', 'F']},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH1_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH1,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
	]

	return config_wh1_new