from models.create_location_models.model_location_pg import KeyLoc
from models.create_location_models.location_pg_new.model_location_pg_new import RackConfig_New

def list_config_wh3_new() -> list:
	'''	Location hệ thống mới chỉ thay đổi location rack
		Location ST, Floor vẫn chạy bên location cũ
	'''
	config_wh3_new = [
		#Rack G01
		RackConfig_New(
			name_rack = ['G01'],
			from_bin = 1,
			to_bin = 32,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.ST,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.LOW,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
        RackConfig_New(
			name_rack = ['GS1'],
			from_bin = 1,
			to_bin = 32,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.SV,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.LOW,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
        #Rack G02
		RackConfig_New(
			name_rack = ['G02'],
			from_bin = 1,
			to_bin = 32,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.ST,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.LOW,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
        RackConfig_New(
			name_rack = ['G02'],
			from_bin = 33,
			to_bin = 67,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E', 'F', 'G']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.ST,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
        #Rack G03
		RackConfig_New(
			name_rack = ['G03'],
			from_bin = 1,
			to_bin = 35,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E', 'F', 'G']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
        RackConfig_New(
			name_rack = ['G03'],
			from_bin = 36,
			to_bin = 51,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
            ),
		RackConfig_New(
			name_rack = ['G03'],
			from_bin = 52,
			to_bin = 54,
			level_config = {i:ord(i)-64 for i in ['C', 'D', 'E']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
            ),
		RackConfig_New(
			name_rack = ['G03'],
			from_bin = 55,
			to_bin = 72,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
            ),
        #Rack G04
		RackConfig_New(
			name_rack = ['G04'],
			from_bin = 1,
			to_bin = 18,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
        RackConfig_New(
			name_rack = ['G04'],
			from_bin = 19,
			to_bin = 21,
			level_config = {i:ord(i)-64 for i in ['C', 'D', 'E']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
        RackConfig_New(
			name_rack = ['G04'],
			from_bin = 22,
			to_bin = 22,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
        RackConfig_New(
			name_rack = ['G04'],
			from_bin = 23,
			to_bin = 23,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E', 'F', 'G']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
        RackConfig_New(
			name_rack = ['G04'],
			from_bin = 24,
			to_bin = 26,
			level_config = {i:ord(i)-64 for i in ['D', 'E', 'F', 'G']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
        RackConfig_New(
			name_rack = ['G04'],
			from_bin = 27,
			to_bin = 44,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E', 'F', 'G']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
        #Rack G05
		RackConfig_New(
			name_rack = ['G05'],
			from_bin = 1,
			to_bin = 18,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E', 'F', 'G']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
        RackConfig_New(
			name_rack = ['G05'],
			from_bin = 19,
			to_bin = 21,
			level_config = {i:ord(i)-64 for i in ['D', 'E', 'F', 'G']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
        RackConfig_New(
			name_rack = ['G05'],
			from_bin = 22,
			to_bin = 22,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E', 'F', 'G']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
        RackConfig_New(
			name_rack = ['G05'],
			from_bin = 23,
			to_bin = 35,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E', 'F']},
			ft_prefix_chars = {'G05': 'GT5'},
			ft_prefix_at_level = {'G05': ['A', 'B', 'C', 'D', 'E', 'F']},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
        #Rack G06
		RackConfig_New(
			name_rack = ['G06'],
			from_bin = 1,
			to_bin = 13,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E', 'F']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.ST,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
        RackConfig_New(
			name_rack = ['GS6'],
			from_bin = 12,
			to_bin = 13,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.SV,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH3_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.LOW,
			name_warehouse = KeyLoc.NameWarehouse.WH3,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
    ]
	return config_wh3_new
	