from models.create_location_models.model_location_pg import KeyLoc
from models.create_location_models.location_pg_new.model_location_pg_new import RackConfig_New

def list_config_wh2_new() -> list:
	'''	Location hệ thống mới chỉ thay đổi location rack
		Location ST, Floor vẫn chạy bên location cũ
	'''
	config_wh2_new = [
		#Rack F01
		RackConfig_New(
			name_rack = ['F01'],
			from_bin = 1,
			to_bin = 31,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			ft_prefix_chars = {'F01': 'FT1'},
			ft_prefix_at_level = {'F01': ['B', 'C', 'D']},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH2_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
        #Rack 02
		RackConfig_New(
			name_rack = ['F02'],
			from_bin = 1,
			to_bin = 16,
			level_config = {i:ord(i)-64 for i in ['A']},
			ft_prefix_chars = {'F02': 'FT2'},
			ft_prefix_at_level = {'F02': ['A']},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = 'both',
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH2_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = KeyLoc.Note.TANG_A_LSL_XUONG
			),
        RackConfig_New(
			name_rack = ['F02'],
			from_bin = 17,
			to_bin = 68,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = 'both',
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH2_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
        #F03
		RackConfig_New(
			name_rack = ['F03'],
			from_bin = 1,
			to_bin = 71,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			ft_prefix_chars = {'F03': 'FT3'},
			ft_prefix_at_level = {'F03': ['B']},
			prefix_at_even_odd_bin = 'odd',
			even_odd_both_bin = 'both',
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH2_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
        RackConfig_New(
			name_rack = ['F03'],
			from_bin = 4,
			to_bin = 68,
			level_config = {i:ord(i)-64 for i in ['F']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = 'even',
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH2_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
        #Rack F04
		RackConfig_New(
			name_rack = ['F04'],
			from_bin = 1,
			to_bin = 71,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E', 'F']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = 'both',
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH2_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
        #Rack F05
		RackConfig_New(
			name_rack = ['F05'],
			from_bin = 1,
			to_bin = 71,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E', 'F']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = 'both',
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH2_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
        #Rack F06
		RackConfig_New(
			name_rack = ['F06'],
			from_bin = 1,
			to_bin = 71,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = 'both',
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH2_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
        RackConfig_New(
			name_rack = ['F06'],
			from_bin = 3,
			to_bin = 71,
			level_config = {i:ord(i)-64 for i in ['F']},
			ft_prefix_chars = {},
			ft_prefix_at_level = {},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = 'odd',
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH2_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
        #Rack F07
		RackConfig_New(
			name_rack = ['F07'],
			from_bin = 1,
			to_bin = 36,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D', 'E']},
			ft_prefix_chars = {'F07': 'FT7'},
			ft_prefix_at_level = {'F07': ['C', 'D']},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.DB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH2_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.MEDIUM,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
        RackConfig_New(
			name_rack = ['F07'],
			from_bin = 37,
			to_bin = 66,
			level_config = {i:ord(i)-64 for i in ['A', 'B', 'C', 'D']},
			ft_prefix_chars = {'F07': 'FT7'},
			ft_prefix_at_level = {'F07': ['A', 'B', 'C', 'D']},
			prefix_at_even_odd_bin = None,
			even_odd_both_bin = None,
			list_bin_ho = [],
			location_usage_type = {},
			rack_system_type = KeyLoc.RackSystemType.OB,
			location_storage_type = KeyLoc.LocStorageType.RACK,
			zone = KeyLoc.Zone.WH2_RACK,
			location_category = KeyLoc.LocCategory.STORARE,
			location_product_category = KeyLoc.LocProducCategory.FG_RPM,
			location_hight = KeyLoc.LocHight.HIGHT,
			name_warehouse = KeyLoc.NameWarehouse.WH2,
			stack_limit = 1,
			is_active = 1,
			status_location = KeyLoc.Status_Location.OK,
			note = None
			),
    ]
	return config_wh2_new